### ISSUE TITLE
Facing While Front End Application

### ISSUE THREAD

**Issue by sanyogs** [cattr-app/server-application#113] opened 2023-07-07 11:31 UTC
[root@sup timehome]# /opt/plesk/php/8.2/bin/php /usr/lib64/plesk-9.0/composer.phar install && /opt/plesk/php/8.2/bin/php artisan cattr:install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 175 installs, 0 updates, 0 removals
  - Downloading php-http/discovery (1.16.0)
  - Downloading wikimedia/composer-merge-plugin (v2.1.0)
  - Downloading phpstan/phpdoc-parser (1.20.3)
  - Downloading doctrine/deprecations (v1.0.0)
  - Downloading phpdocumentor/type-resolver (1.7.1)
  - Downloading nikic/php-parser (v4.15.4)
  - Downloading voku/portable-ascii (2.0.1)
  - Downloading symfony/polyfill-php80 (v1.27.0)
  - Downloading symfony/polyfill-mbstring (v1.27.0)
  - Downloading symfony/polyfill-ctype (v1.27.0)
  - Downloading phpoption/phpoption (1.9.1)
  - Downloading graham-campbell/result-type (v1.1.1)
  - Downloading vlucas/phpdotenv (v5.5.0)
  - Downloading symfony/css-selector (v6.2.7)
  - Downloading tijsverkoyen/css-to-inline-styles (2.2.6)
  - Downloading symfony/var-dumper (v6.2.8)
  - Downloading symfony/polyfill-uuid (v1.27.0)
  - Downloading symfony/uid (v6.2.7)
  - Downloading symfony/routing (v6.2.8)
  - Downloading symfony/process (v6.2.8)
  - Downloading symfony/polyfill-php72 (v1.27.0)
  - Downloading symfony/polyfill-intl-normalizer (v1.27.0)
  - Downloading symfony/polyfill-intl-idn (v1.27.0)
  - Downloading symfony/mime (v6.2.7)
  - Downloading psr/container (2.0.2)
  - Downloading symfony/service-contracts (v3.2.1)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher-contracts (v3.2.1)
  - Downloading symfony/event-dispatcher (v6.2.8)
  - Downloading psr/log (2.0.0)
  - Downloading doctrine/lexer (3.0.0)
  - Downloading egulias/email-validator (4.0.1)
  - Downloading symfony/mailer (v6.2.8)
  - Downloading symfony/deprecation-contracts (v3.2.1)
  - Downloading symfony/http-foundation (v6.2.8)
  - Downloading symfony/error-handler (v6.2.9)
  - Downloading symfony/http-kernel (v6.2.9)
  - Downloading symfony/finder (v6.2.7)
  - Downloading symfony/polyfill-intl-grapheme (v1.27.0)
  - Downloading symfony/string (v6.2.8)
  - Downloading symfony/console (v6.2.8)
  - Downloading ramsey/collection (2.0.0)
  - Downloading brick/math (0.11.0)
  - Downloading ramsey/uuid (4.7.4)
  - Downloading psr/simple-cache (3.0.0)
  - Downloading nunomaduro/termwind (v1.15.1)
  - Downloading symfony/translation-contracts (v3.2.1)
  - Downloading symfony/translation (v6.2.8)
  - Downloading nesbot/carbon (2.66.0)
  - Downloading monolog/monolog (3.3.1)
  - Downloading league/mime-type-detection (1.11.0)
  - Downloading league/flysystem (3.14.0)
  - Downloading nette/utils (v4.0.0)
  - Downloading nette/schema (v1.2.3)
  - Downloading dflydev/dot-access-data (v3.0.2)
  - Downloading league/config (v1.2.0)
  - Downloading league/commonmark (2.4.0)
  - Downloading laravel/serializable-closure (v1.3.0)
  - Downloading guzzlehttp/uri-template (v1.0.1)
  - Downloading fruitcake/php-cors (v1.2.0)
  - Downloading webmozart/assert (1.11.0)
  - Downloading dragonmantank/cron-expression (v3.3.2)
  - Downloading doctrine/inflector (2.0.6)
  - Downloading laravel/framework (v10.9.0)
  - Downloading psr/cache (3.0.0)
  - Downloading doctrine/event-manager (2.0.0)
  - Downloading doctrine/cache (2.2.0)
  - Downloading doctrine/dbal (3.6.2)
  - Downloading composer/class-map-generator (1.0.0)
  - Downloading barryvdh/reflection-docblock (v2.1.0)
  - Downloading psr/http-message (1.1)
  - Downloading symfony/psr-http-message-bridge (v2.2.0)
  - Downloading ringcentral/psr7 (1.3.0)
  - Downloading react/event-loop (v1.3.0)
  - Downloading evenement/evenement (v3.0.1)
  - Downloading react/stream (v1.2.0)
  - Downloading react/promise (v2.9.0)
  - Downloading react/promise-timer (v1.9.0)
  - Downloading react/cache (v1.2.0)
  - Downloading react/dns (v1.10.0)
  - Downloading react/socket (v1.12.0)
  - Downloading react/promise-stream (v1.5.0)
  - Downloading fig/http-message-util (1.1.5)
  - Downloading react/http (v1.8.0)
  - Downloading paragonie/random_compat (v9.99.100)
  - Downloading paragonie/sodium_compat (v1.19.0)
  - Downloading psr/http-client (1.0.2)
  - Downloading ralouphie/getallheaders (3.0.3)
  - Downloading psr/http-factory (1.0.2)
  - Downloading guzzlehttp/psr7 (2.5.0)
  - Downloading guzzlehttp/promises (1.5.2)
  - Downloading guzzlehttp/guzzle (7.5.1)
  - Downloading pusher/pusher-php-server (7.2.2)
  - Downloading facade/ignition-contracts (1.0.2)
  - Downloading ratchet/rfc6455 (v0.3.1)
  - Downloading cboden/ratchet (v0.4.4)
  - Downloading beyondcode/laravel-websockets (1.14.0)
  - Downloading czproject/git-php (v4.1.0)
  - Downloading elhebert/laravel-sri (3.2.0)
  - Downloading erusev/parsedown (1.7.4)
  - Downloading fakerphp/faker (v1.21.0)
  - Downloading league/fractal (0.20.1)
  - Downloading flugger/laravel-responder (v3.3.0)
  - Downloading http-interop/http-factory-guzzle (1.2.0)
  - Downloading intervention/image (2.7.2)
  - Downloading jean85/pretty-package-versions (2.0.5)
  - Downloading laminas/laminas-diactoros (2.25.2)
  - Downloading laravel/octane (v1.5.4)
  - Downloading laravel/sanctum (v3.2.3)
  - Downloading laravel/telescope (v4.14.2)
  - Downloading psy/psysh (v0.11.15)
  - Downloading markbaker/matrix (3.0.1)
  - Downloading markbaker/complex (3.0.2)
  - Downloading myclabs/php-enum (1.8.4)
  - Downloading maennchen/zipstream-php (v2.4.0)
  - Downloading ezyang/htmlpurifier (v4.16.0)
  - Downloading phpoffice/phpspreadsheet (1.28.0)
  - Downloading composer/semver (3.3.2)
  - Downloading maatwebsite/excel (3.1.48)
  - Downloading phayes/geophp (1.2)
  - Downloading matanyadaev/laravel-eloquent-spatial (3.1.2)
  - Downloading mockery/mockery (1.5.1)
  - Downloading setasign/fpdi (v2.3.7)
  - Downloading php-http/message-factory (1.1.0)
  - Downloading myclabs/deep-copy (1.11.1)
  - Downloading mpdf/mpdf (v8.1.5)
  - Downloading nunomaduro/collision (v7.5.2)
  - Downloading nwidart/laravel-modules (v10.0.0)
  - Downloading symfony/options-resolver (v6.2.7)
  - Downloading clue/stream-filter (v1.6.0)
  - Downloading php-http/message (1.14.0)
  - Downloading php-http/promise (1.1.0)
  - Downloading php-http/httplug (2.4.0)
  - Downloading php-http/client-common (2.6.1)
  - Downloading sebastian/diff (5.0.1)
  - Downloading phpunit/php-file-iterator (4.0.1)
  - Downloading phpunit/php-code-coverage (10.1.1)
  - Downloading phpunit/phpunit (10.1.2)
  - Downloading nyholm/psr7 (1.7.0)
  - Downloading symfony/http-client-contracts (v3.2.1)
  - Downloading symfony/http-client (v6.2.9)
  - Downloading sentry/sentry (3.17.0)
  - Downloading sentry/sentry-laravel (3.3.3)
  - Installing php-http/discovery (1.16.0): Extracting archive
  - Installing wikimedia/composer-merge-plugin (v2.1.0): Extracting archive
  - Installing phpstan/phpdoc-parser (1.20.3): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing doctrine/deprecations (v1.0.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.7.1): Extracting archive
  - Installing nikic/php-parser (v4.15.4): Extracting archive
  - Installing voku/portable-ascii (2.0.1): Extracting archive
  - Installing symfony/polyfill-php80 (v1.27.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.27.0): Extracting archive
  - Installing phpoption/phpoption (1.9.1): Extracting archive
  - Installing graham-campbell/result-type (v1.1.1): Extracting archive
  - Installing vlucas/phpdotenv (v5.5.0): Extracting archive
  - Installing symfony/css-selector (v6.2.7): Extracting archive
  - Installing tijsverkoyen/css-to-inline-styles (2.2.6): Extracting archive
  - Installing symfony/var-dumper (v6.2.8): Extracting archive
  - Installing symfony/polyfill-uuid (v1.27.0): Extracting archive
  - Installing symfony/uid (v6.2.7): Extracting archive
  - Installing symfony/routing (v6.2.8): Extracting archive
  - Installing symfony/process (v6.2.8): Extracting archive
  - Installing symfony/polyfill-php72 (v1.27.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.27.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.27.0): Extracting archive
  - Installing symfony/mime (v6.2.7): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.2.1): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.2.1): Extracting archive
  - Installing symfony/event-dispatcher (v6.2.8): Extracting archive
  - Installing psr/log (2.0.0): Extracting archive
  - Installing doctrine/lexer (3.0.0): Extracting archive
  - Installing egulias/email-validator (4.0.1): Extracting archive
  - Installing symfony/mailer (v6.2.8): Extracting archive
  - Installing symfony/deprecation-contracts (v3.2.1): Extracting archive
  - Installing symfony/http-foundation (v6.2.8): Extracting archive
  - Installing symfony/error-handler (v6.2.9): Extracting archive
  - Installing symfony/http-kernel (v6.2.9): Extracting archive
  - Installing symfony/finder (v6.2.7): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.27.0): Extracting archive
  - Installing symfony/string (v6.2.8): Extracting archive
  - Installing symfony/console (v6.2.8): Extracting archive
  - Installing ramsey/collection (2.0.0): Extracting archive
  - Installing brick/math (0.11.0): Extracting archive
  - Installing ramsey/uuid (4.7.4): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing nunomaduro/termwind (v1.15.1): Extracting archive
  - Installing symfony/translation-contracts (v3.2.1): Extracting archive
  - Installing symfony/translation (v6.2.8): Extracting archive
  - Installing nesbot/carbon (2.66.0): Extracting archive
  - Installing monolog/monolog (3.3.1): Extracting archive
  - Installing league/mime-type-detection (1.11.0): Extracting archive
  - Installing league/flysystem (3.14.0): Extracting archive
  - Installing nette/utils (v4.0.0): Extracting archive
  - Installing nette/schema (v1.2.3): Extracting archive
  - Installing dflydev/dot-access-data (v3.0.2): Extracting archive
  - Installing league/config (v1.2.0): Extracting archive
  - Installing league/commonmark (2.4.0): Extracting archive
  - Installing laravel/serializable-closure (v1.3.0): Extracting archive
  - Installing guzzlehttp/uri-template (v1.0.1): Extracting archive
  - Installing fruitcake/php-cors (v1.2.0): Extracting archive
  - Installing webmozart/assert (1.11.0): Extracting archive
  - Installing dragonmantank/cron-expression (v3.3.2): Extracting archive
  - Installing doctrine/inflector (2.0.6): Extracting archive
  - Installing laravel/framework (v10.9.0): Extracting archive
  - Installing psr/cache (3.0.0): Extracting archive
  - Installing doctrine/event-manager (2.0.0): Extracting archive
  - Installing doctrine/cache (2.2.0): Extracting archive
  - Installing doctrine/dbal (3.6.2): Extracting archive
  - Installing composer/pcre (3.1.0): Extracting archive
  - Installing composer/class-map-generator (1.0.0): Extracting archive
  - Installing barryvdh/reflection-docblock (v2.1.0): Extracting archive
  - Installing barryvdh/laravel-ide-helper (v2.13.0): Extracting archive
  - Installing phpdocumentor/graphviz (1.0.4): Extracting archive
  - Installing beyondcode/laravel-er-diagram-generator (2.0.0): Extracting archive
  - Installing psr/http-message (1.1): Extracting archive
  - Installing symfony/psr-http-message-bridge (v2.2.0): Extracting archive
  - Installing ringcentral/psr7 (1.3.0): Extracting archive
  - Installing react/event-loop (v1.3.0): Extracting archive
  - Installing evenement/evenement (v3.0.1): Extracting archive
  - Installing react/stream (v1.2.0): Extracting archive
  - Installing react/promise (v2.9.0): Extracting archive
  - Installing react/promise-timer (v1.9.0): Extracting archive
  - Installing react/cache (v1.2.0): Extracting archive
  - Installing react/dns (v1.10.0): Extracting archive
  - Installing react/socket (v1.12.0): Extracting archive
  - Installing react/promise-stream (v1.5.0): Extracting archive
  - Installing fig/http-message-util (1.1.5): Extracting archive
  - Installing react/http (v1.8.0): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing paragonie/sodium_compat (v1.19.0): Extracting archive
  - Installing psr/http-client (1.0.2): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.0.2): Extracting archive
  - Installing guzzlehttp/psr7 (2.5.0): Extracting archive
  - Installing guzzlehttp/promises (1.5.2): Extracting archive
  - Installing guzzlehttp/guzzle (7.5.1): Extracting archive
  - Installing pusher/pusher-php-server (7.2.2): Extracting archive
  - Installing facade/ignition-contracts (1.0.2): Extracting archive
  - Installing ratchet/rfc6455 (v0.3.1): Extracting archive
  - Installing cboden/ratchet (v0.4.4): Extracting archive
  - Installing beyondcode/laravel-websockets (1.14.0): Extracting archive
  - Installing czproject/git-php (v4.1.0): Extracting archive
  - Installing elhebert/laravel-sri (3.2.0): Extracting archive
  - Installing erusev/parsedown (1.7.4): Extracting archive
  - Installing fakerphp/faker (v1.21.0): Extracting archive
  - Installing league/fractal (0.20.1): Extracting archive
  - Installing flugger/laravel-responder (v3.3.0): Extracting archive
  - Installing http-interop/http-factory-guzzle (1.2.0): Extracting archive
  - Installing intervention/image (2.7.2): Extracting archive
  - Installing itsgoingd/clockwork (v5.1.12): Extracting archive
  - Installing jean85/pretty-package-versions (2.0.5): Extracting archive
  - Installing laminas/laminas-diactoros (2.25.2): Extracting archive
  - Installing laravel/octane (v1.5.4): Extracting archive
  - Installing laravel/sanctum (v3.2.3): Extracting archive
  - Installing laravel/telescope (v4.14.2): Extracting archive
  - Installing psy/psysh (v0.11.15): Extracting archive
  - Installing laravel/tinker (v2.8.1): Extracting archive
  - Installing markbaker/matrix (3.0.1): Extracting archive
  - Installing markbaker/complex (3.0.2): Extracting archive
  - Installing myclabs/php-enum (1.8.4): Extracting archive
  - Installing maennchen/zipstream-php (v2.4.0): Extracting archive
  - Installing ezyang/htmlpurifier (v4.16.0): Extracting archive
  - Installing phpoffice/phpspreadsheet (1.28.0): Extracting archive
  - Installing composer/semver (3.3.2): Extracting archive
  - Installing maatwebsite/excel (3.1.48): Extracting archive
  - Installing phayes/geophp (1.2): Extracting archive
  - Installing matanyadaev/laravel-eloquent-spatial (3.1.2): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.5.1): Extracting archive
  - Installing setasign/fpdi (v2.3.7): Extracting archive
  - Installing php-http/message-factory (1.1.0): Extracting archive
  - Installing myclabs/deep-copy (1.11.1): Extracting archive
  - Installing mpdf/mpdf (v8.1.5): Extracting archive
  - Installing filp/whoops (2.15.2): Extracting archive
  - Installing nunomaduro/collision (v7.5.2): Extracting archive
  - Installing nwidart/laravel-modules (v10.0.0): Extracting archive
  - Installing symfony/options-resolver (v6.2.7): Extracting archive
  - Installing clue/stream-filter (v1.6.0): Extracting archive
  - Installing php-http/message (1.14.0): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing php-http/httplug (2.4.0): Extracting archive
  - Installing php-http/client-common (2.6.1): Extracting archive
  - Installing sebastian/version (4.0.1): Extracting archive
  - Installing sebastian/type (4.0.0): Extracting archive
  - Installing sebastian/recursion-context (5.0.0): Extracting archive
  - Installing sebastian/object-reflector (3.0.0): Extracting archive
  - Installing sebastian/object-enumerator (5.0.0): Extracting archive
  - Installing sebastian/global-state (6.0.0): Extracting archive
  - Installing sebastian/exporter (5.0.0): Extracting archive
  - Installing sebastian/environment (6.0.1): Extracting archive
  - Installing sebastian/diff (5.0.1): Extracting archive
  - Installing sebastian/comparator (5.0.0): Extracting archive
  - Installing sebastian/code-unit (2.0.0): Extracting archive
  - Installing sebastian/cli-parser (2.0.0): Extracting archive
  - Installing phpunit/php-timer (6.0.0): Extracting archive
  - Installing phpunit/php-text-template (3.0.0): Extracting archive
  - Installing phpunit/php-invoker (4.0.0): Extracting archive
  - Installing phpunit/php-file-iterator (4.0.1): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/lines-of-code (2.0.0): Extracting archive
  - Installing sebastian/complexity (3.0.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (3.0.0): Extracting archive
  - Installing phpunit/php-code-coverage (10.1.1): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing phpunit/phpunit (10.1.2): Extracting archive
  - Installing roave/security-advisories (dev-latest 5eb9b05)
  - Installing nyholm/psr7 (1.7.0): Extracting archive
  - Installing symfony/http-client-contracts (v3.2.1): Extracting archive
  - Installing symfony/http-client (v6.2.9): Extracting archive
  - Installing sentry/sentry (3.17.0): Extracting archive
  - Installing sentry/sdk (3.3.0)
  - Installing sentry/sentry-laravel (3.3.3): Extracting archive
  - Installing squizlabs/php_codesniffer (3.7.2): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  barryvdh/laravel-ide-helper ....................................................................................... DONE
  beyondcode/laravel-er-diagram-generator ........................................................................... DONE
  beyondcode/laravel-websockets ..................................................................................... DONE
  elhebert/laravel-sri .............................................................................................. DONE
  flugger/laravel-responder ......................................................................................... DONE
  intervention/image ................................................................................................ DONE
  itsgoingd/clockwork ............................................................................................... DONE
  laravel/octane .................................................................................................... DONE
  laravel/sanctum ................................................................................................... DONE
  laravel/telescope ................................................................................................. DONE
  laravel/tinker .................................................................................................... DONE
  maatwebsite/excel ................................................................................................. DONE
  matanyadaev/laravel-eloquent-spatial .............................................................................. DONE
  nesbot/carbon ..................................................................................................... DONE
  nunomaduro/collision .............................................................................................. DONE
  nunomaduro/termwind ............................................................................................... DONE
  nwidart/laravel-modules ........................................................................................... DONE
  sentry/sentry-laravel ............................................................................................. DONE

> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  Publishing [laravel-assets] assets.  

  Copying directory [vendor/laravel/telescope/public] to [public/vendor/telescope] .................................. DONE

111 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php -r "file_exists('.env') || copy('.env.example', '.env');"

   ERROR  Command "cattr:install" is not defined. Did you mean one of these?  

  ⇂ cattr:intervals:apps:clear-expired  
  ⇂ cattr:intervals:dedupe  
  ⇂ cattr:mail:test  
  ⇂ cattr:make:admin  
  ⇂ cattr:module:version  
  ⇂ cattr:register  
  ⇂ cattr:reset  
  ⇂ cattr:screenshots:rotate  
  ⇂ cattr:set:language  
  ⇂ cattr:set:timezone  
  ⇂ cattr:version  
  ⇂ migrate:install  
  ⇂ module:install  
  ⇂ octane:install  
  ⇂ telescope:install  

[root@sup timehome]#

**Comment by vermorag** [comment] 2023-11-08 03:39
Duplicate of #115

**Closed by vermorag** 2023-11-08 03:39 UTC
